### ISSUE TITLE
exception raised after ddf commands

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#122]
for example:

```
2020-02-11 16:32:09 ddf_utils.package INFO generating ddf schema, may take some time...
Done.
Exception ignored in: <function Pool.__del__ at 0x10c35f9d0>
Traceback (most recent call last):
  File "/Users/semio/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/Users/semio/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
Exception ignored in: <function Pool.__del__ at 0x10c35f9d0>
Traceback (most recent call last):
  File "/Users/semio/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/Users/semio/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by semio** [comment]
it was caused by dask and can be fixed with updating dask to latest version
