### ISSUE TITLE
Datapackage creation crashes if one of the datapoint files contains an empty line

### ISSUE THREAD

**Issue by angieskazka** [semio/ddf_utils#126]
if one of the datapoint files contains an empty line, `ddf create_datapackage .` command would crash

test like this

```
geo,time,indicator
afg,1989,12
afg,1990,13
afg,1991,14
```

```
geo,time,indicator
afg,1989,12
,,
afg,1990,13
afg,1991,14
```

![image](https://user-images.githubusercontent.com/3648190/83776646-b3c4be80-a688-11ea-8c0d-af508b9ed10c.png)

this is not helpful, because searching for `{nan}` doesn't find anything
and error message doesn't say which file contains the problem

```
chanter:ddf--open_numbers--yearly_data_as_daily angie$ ddf create_datapackage . --overwrite
backing up previous datapackage.json...
2020-06-04 17:19:11 WARNING skipping file datapackage.json
2020-06-04 17:19:11 WARNING skipping file datapackage.json.bak
2020-06-04 17:19:11 INFO generating ddf schema, may take some time...
2020-06-04 17:19:11 CRITICAL geo column contains entity which is not in entity file: {nan}
Traceback (most recent call last):
  File "/usr/local/bin/ddf", line 8, in <module>
    sys.exit(ddf())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddf_utils/cli.py", line 89, in create_datapackage
    res = get_datapackage(path, use_existing=False, progress_bar=progress_bar)
  File "/usr/local/lib/python3.7/site-packages/ddf_utils/package.py", line 80, in get_datapackage
    datapackage_new = create_datapackage(path, progress_bar=progress_bar)
  File "/usr/local/lib/python3.7/site-packages/ddf_utils/package.py", line 249, in create_datapackage
    dp.ddfSchema = dp.generate_ddf_schema(progress_bar=progress_bar)
  File "/usr/local/lib/python3.7/site-packages/ddf_utils/model/package.py", line 439, in generate_ddf_schema
    for kvo in g:
  File "/usr/local/lib/python3.7/site-packages/ddf_utils/model/package.py", line 362, in _gen_key_value_object
    raise ValueError("entity mismatch")
ValueError: entity mismatch
```

**Comment by semio** [comment]
Thanks for reporting, I agree that the message is not obvious enough. Actually if you run it in debug mode it will show the file with problem:

![捕获](https://user-images.githubusercontent.com/351856/83830508-eec20300-a717-11ea-81fc-71434627d70d.PNG)

I will change it so even not running debug mode it will output this message.

Nan is a value without text, so you can not search for it.. I think maybe we could add line number to the error message to make it more clear too.

**Comment by semio** [comment]
Ah actually I have already changed the error message, could you try upgrading ddf_utils and try again?
