### ISSUE TITLE
"JSONDecodeError: Expecting value" using IHME bulk_download

### ISSUE THREAD

**Issue by franperr** [semio/ddf_utils#130]
Hi, Thanks for your package, it seems to be useful to download data from the GBD db (in particular in my case where I have to download the same data for several countries). I'm following the example in doc, modifying according to my needs. I have tried several variations, but I always receive the same error (below the code).

Interestingly, on the first call, I receive by email the link to the GBD webpage where I can download the result. However, I can use it only once in a row (I suppose there is some kind of timeout, because if I try several hours later I receive again the email).

```
from ddf_utils.factory.ihme import IHMELoader
l = IHMELoader()
md = l.load_metadata()
l.bulk_download('/tmp/', 
                context='cause', 
                version=7266, 
                year=[1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019], 
                email='xxx@xxx.com', 
                metric=[1,2,3], 
                sex=[1,2], 
                measure=[1,2,3,4],
                age=22,
                location=6,
                cause=[294,295,955,298,948,949,950,300,393,394,395,396,397,398,399,956,297,954,934,946,947,322,328,329,957,302,958,319,320,959,321,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,405,843,935,936,365,961,332,337,338,339,340,341,342,400,401,402,403,404,408,962,366,367,368,369,370,995,374,375,376,741,379,380,381,382,383,384,385,386,387,388,389,390,391,409,410,444,447,450,411,414,441,417,418,419,420,996,1021,453,456,423,426,459,462,849,850,429,432,435,465,438,468,471,474,477,480,483,484,485,486,487,845,846,847,848,943,1022,490,964,965,966,967,491,492,493,494,495,496,497,498,504,968,969,970,499,942,938,944,500,501,502,503,1023,508,509,510,511,512,513,514,515,516,520,526,521,522,523,524,971,525,992,527,528,536,529,530,531,532,533,534,535,541,542,543,544,545,546,554,972,547,548,557,558,559,567,568,569,570,571,572,573,574,575,578,579,582,585,973,560,561,562,563,564,565,566,974,587,975,976,589,997,998,591,592,593,588,653,654,977,978,979,655,980,656,657,658,659,660,661,662,663,664,665,668,669,981,670,671,672,999,1000,675,674,679,626,627,628,1014,1015,1016,1017,630,631,632,639,640,641,642,643,644,645,646,647,648,649,650,651,652,594,595,596,597,598,602,603,604,605,606,607,608,609,612,613,614,837,615,838,616,839,618,619,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,703,704,705,707,708,709,710,711,712,713,714,715,842,729,716,717,718,721,723,724,725,726,941,727,945,854,1029,1026,1027,1028],
                idsOrNames='both')

```

## Error:

```

Traceback (most recent call last):

  File "<ipython-input-6-b21f2f498647>", line 1, in <module>
    runfile('/home/peyu/Bureau/mapament/GBD/download.py', wdir='/home/peyu/Bureau/mapament/GBD')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/peyu/Bureau/mapament/GBD/download.py", line 15, in <module>
    l.bulk_download('/tmp/',

  File "/usr/local/lib/python3.8/dist-packages/ddf_utils/factory/ihme.py", line 140, in bulk_download
    for u in self.download_links(url):

  File "/usr/local/lib/python3.8/dist-packages/ddf_utils/factory/ihme.py", line 79, in download_links
    res_json = session.get(url).json()

  File "/usr/lib/python3/dist-packages/requests/models.py", line 888, in json
    return complexjson.loads(

  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)

  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value
```

**Comment by semio** [comment]
Hi, thanks for reporting the issue. Apparently IHME's json endpoint had some changes which cause this issue. I am looking into it now

**Comment by franperr** [comment]
thanks, the last commit you did 4 hours ago seems to work !
