### ISSUE TITLE
Bug in build_dag

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#44]
Platform: windows 10
ddf_utils: 0.2.7 (2016-12-06)

When running a recipe (any), in this case https://github.com/cjbackman/ddf--sodertornsmodellen/blob/master/etl/recipes/sodertornsmodellen.yaml

```
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\site-packages\orderedattrdict\__init__.py", line 31, in __getattr__
    return self[name]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\Scripts\ddf-script.py", line 11, in <module>
    load_entry_point('ddf-utils==0.2.7.dev0', 'console_scripts', 'ddf')()
  File "c:\program files (x86)\python35-32\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python35-32\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python35-32\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python35-32\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\ddf_utils\cli.py", line 93, in run_recipe
    res = chef.run_recipe(recipe)
  File "c:\program files (x86)\python35-32\lib\site-packages\ddf_utils\chef\cook.py", line 228, in run_recipe
    dag = build_dag(recipe)
  File "c:\program files (x86)\python35-32\lib\site-packages\ddf_utils\chef\cook.py", line 180, in build_dag
    task = ProcedureNode(proc.result, proc, dag)
  File "c:\program files (x86)\python35-32\lib\site-packages\orderedattrdict\__init__.py", line 33, in __getattr__
    raise AttributeError(name)
AttributeError: result
```

**Comment by semio** [comment]
Hi @jheeffer 

Regrading ddf--sodertornsmodellen, please modify the recipe:

- add `result` to procedures under `concepts` and `entities`
- modify the `add_concepts` procedure using the format in https://github.com/semio/ddf_utils/issues/40#issuecomment-264113935

I guess other recipes that have this error are because the missing of `result` parameter in the procedure block. Please try to add them and run again.

Sorry about the breaking changes, I will be careful next time
