### ISSUE TITLE
error in datapackage creation for dummy dataset

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#63]
dataset: ddf--gapminder--dummy_companies

```
Traceback (most recent call last):
  File "/Users/semio/.pyenv/versions/3.6.0/bin/ddf", line 11, in <module>
    load_entry_point('ddf-utils', 'console_scripts', 'ddf')()
  File "/Users/semio/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/semio/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/semio/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/semio/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/semio/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/semio/src/work/Gapminder/libs/ddf_utils/ddf_utils/cli.py", line 82, in create_datapackage
    dp.generate_ddfschema()
  File "/Users/semio/src/work/Gapminder/libs/ddf_utils/ddf_utils/model/datapackage.py", line 122, in generate_ddfschema
    _add_to_schema(kvo)
  File "/Users/semio/src/work/Gapminder/libs/ddf_utils/ddf_utils/model/datapackage.py", line 110, in _add_to_schema
    hash_val = key + '--' + resource_schema['value']
TypeError: must be str, not float
```

**Comment by semio** [comment]
@jheeffer reason of this problem: 

Because there is an entity file `ddf--entities--project` which has only one column, so the `resource_schema['value']` value is `null` in this case. So we can't create hash. We should take care of this case.

The line in you pseudo code is `hash = key + '--' + resourceSchema.value` in addToSchema()

**Comment by jheeffer** [comment]
Oh right, didn't think that through enough yes, thanks!
