### ISSUE TITLE
Can't run ddf utils on windows

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#67]
I was trying `ddf` or `ddf --help` but got the errors below.

I tried 
`pip3 uninstall ddf-utils`
`pip uninstall ddf-utils`
`pip uninstall git+https://github.com/semio/ddf_utils.git`
`pip3 uninstall git+https://github.com/semio/ddf_utils.git`
followed by
`pip3 install git+https://github.com/semio/ddf_utils.git`

Still the same error. System: Win10 with Python 3.6.1.

```
PS C:\github\open-numbers\ddf--unpop--wpp_population> ddf
Traceback (most recent call last):
  File "C:\Users\Jasper Heeffer\AppData\Local\Programs\Python\Python36-32\Scripts\ddf-script.py", line 11, in <module>
    load_entry_point('ddf-utils==0.2.19', 'console_scripts', 'ddf')()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\__init__.py", line 4, in <module>
    from .ddf_reader import DDF
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\ddf_reader.py", line 8, in <module>
    from .datapackage import get_datapackage
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\datapackage.py", line 9, in <module>
    from .model.package import Datapackage
ModuleNotFoundError: No module named 'ddf_utils.model'
PS C:\github\open-numbers\ddf--unpop--wpp_population> ddf --help
Traceback (most recent call last):
  File "C:\Users\Jasper Heeffer\AppData\Local\Programs\Python\Python36-32\Scripts\ddf-script.py", line 11, in <module>
    load_entry_point('ddf-utils==0.2.19', 'console_scripts', 'ddf')()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\__init__.py", line 4, in <module>
    from .ddf_reader import DDF
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\ddf_reader.py", line 8, in <module>
    from .datapackage import get_datapackage
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\datapackage.py", line 9, in <module>
    from .model.package import Datapackage
ModuleNotFoundError: No module named 'ddf_utils.model'
```

**Comment by semio** [comment]
Hi @jheeffer,

The issue should be fixed and you can try `pip install -U ddf_utils` to get latest version and try again. I saw an other issue on windows, see if you also have this one: #68
