### ISSUE TITLE
from_csv without input parameter doesn't work

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#91]
From the code I get that no input parameter should default to all files in the current directory. However, when I leave it off I get an error because `os.path.isfile(input)` needs a string and input is not a string
https://github.com/semio/ddf_utils/blob/6a2a545c368ff1b64e4211baeb9d51509f2a1d71/ddf_utils/cli.py#L307

```
c:\Users\Jasper Heeffer\Documents\test>ddf from_csv -o ./output
Traceback (most recent call last):
  File "C:\Users\Jasper Heeffer\AppData\Local\Programs\Python\Python36-32\Scripts\ddf-script.py", line 11, in <module>
    load_entry_point('ddf-utils==0.3.3', 'console_scripts', 'ddf')()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\ddf_utils\cli.py", line 307, in from_csv
    if os.path.isfile(input):
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by semio** [comment]
@jheeffer my intention was that users should provide `input` and `output`. Then if `input` is a directory, it will process all files in that directory. For now you can set `-i .` to make it work

**Comment by jheeffer** [comment]
Okay! That wasn't clear to me : ) Default input working dir is good too : )

**Comment by semio** [comment]
close because we have documentation for this function now.
